create database QUANLYSINHVIEN;
USE QUANLYSINHVIEN;
CREATE TABLE CLASS(
CLASSID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
CLASSNAME VARCHAR(60) NOT NULL,
STARDATE DATETIME NOT NULL,
STATUS BIT
);
CREATE TABLE STUDENT(
STUDENTID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
STUDENTNAME VARCHAR(30) NOT NULL,
ADDRESS VARCHAR(50),
PHONE VARCHAR(20),
STATUS BIT,
CLASSID INT NOT NULL,
FOREIGN KEY (CLASSID) REFERENCES CLASS(CLASSID)
);
CREATE TABLE SUBJECT(
SUBID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
SUBNAME VARCHAR(30) NOT NULL,
CREDIT TINYINT NOT NULL DEFAULT 1 CHECK(CREDIT >= 1),
STATUS BIT DEFAULT 1
);
CREATE TABLE MARK(
MARKID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
SUBID INT NOT NULL,
STUDENTID INT NOT NULL,
MARK FLOAT DEFAULT 0 CHECK (MARK BETWEEN 0 AND 100),
EXAMTIMES TINYINT DEFAULT 1,
UNIQUE(SUBID, STUDENTID),
FOREIGN KEY (SUBID) REFERENCES SUBJECT(SUBID),
FOREIGN KEY (STUDENTID) REFERENCES STUDENT(STUDENTID)
);
